name: Build and Publish to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    # Permite executar e compilar binários ARM em runners x86 do GitHub
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Autenticação no Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build simples focado apenas em ARM64 usando a CLI padrão do Docker
    - name: Build and push Docker image
      run: |
        docker build \
          --platform linux/arm64 \
          --no-cache \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/img-api-bitcoin:latest \
          -f ./Dockerfile .
        
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/img-api-bitcoin:latest
